### PR TITLE
Upgrade serde-protobuf to serde 1.0.2 and serde_value 0.5.0

### PR DESCRIPTION
**Pull request by sevagh**
This upgrades the serde-protobuf sub-directory/crate to serde 1.0.2 (alongside serde_value upgrade to 0.5.0).

### CODE REVIEW

**Comment by sevagh** [comment]
I plugged this into my crate pq and everything "works":

```
serde = "1.0.2"
serde-value = "0.5.0"
serde_json = "1.0.1"
serde-protobuf = { path = "serde-protobuf", version = "0.5.0" }
```

That local path is my local copy of `rq/serde-protobuf` with these PR changes.

**Comment by sevagh** [comment]
Also this needs to have `cargo fmt` run on it but when I run `cargo fmt` it changes all the files so I'm not sure about your formatting rules.

**Comment by dflemstr** [comment]
Hey, thanks for the contribution! One of the reasons why I keep `serde-protobuf` and `serde-avro` in this repo is that I want them to always work together with `rq`, so that would mean upgrading `rq` and `serde-avro` to 1.0 as well.  However if you want this merged in we can also remove the path dependency relation from `rq` to `serde-protobuf` so that the travis build passes.

**Comment by dflemstr** [comment]
(I'm referring to this of course:)

```
error[E0277]: the trait bound `&mut serde_protobuf::de::Deserializer<'_>: serde::Deserializer` is not satisfied
  --> src/value/protobuf.rs:27:19
   |
27 |             match serde::Deserialize::deserialize(&mut self.0) {
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::Deserializer` is not implemented for `&mut serde_protobuf::de::Deserializer<'_>`
   |
   = note: required by `serde::Deserialize::deserialize`
error: aborting due to previous error
error: Could not compile `record-query`.
```

**Comment by sevagh** [comment]
I don't mind working more on this to add commits for `serde-avro` and `rq` before it's merged :)

**Comment by dflemstr** [comment]
@sevagh it would probably be easier for you to do the changes to `serde-avro` and `rq` since you have already learnt `serde` 1.0 and I won't have time to address this any time soon (super busy day job :) ).

However if you really can't be bothered feel free to just push a commit decoupling the two and I will deal with upgrading the other crates at a later date.

**Comment by sevagh** [comment]
On it.

**Comment by sevagh** [comment]
I'm having more trouble than I thought for `serde-avro`. I'm still interested in figuring out how to solve it, but how about we do the decoupling in the meanwhile so that you can merge/release `serde-protobuf` and I'll make separate PRs for `serde-avro` and `rq`?

**Comment by dflemstr** [comment]
Makes sense!

**Comment by sevagh** [comment]
Making the commit to decouple and do some code formatting.

**Comment by sevagh** [comment]
Travis passes now.

**Comment by dflemstr** [comment]
The workspace still needs to contain all libraries for the CI to make sense. But I can fix that later (I'm traveling so I have limited access to this project)

**Pull request merged**
